# Generated by Django 5.0.4 on 2024-05-11 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0002_replycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replycomment',
            name='cmt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_comments', to='site1.comment'),
        ),
    ]
