# Generated by Django 5.0.4 on 2024-05-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0006_post_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('calories', models.IntegerField()),
                ('classification', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='site1/static/site1/post_images/')),
            ],
        ),
    ]
