# Generated by Django 5.0.4 on 2024-05-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0007_fruit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='classification',
            field=models.CharField(choices=[('HIGH_CALORIES', 'Hoa quả nhiều calo'), ('LOW_CALORIES', 'Ít calo'), ('MODERATE_CALORIES', 'Calo vừa phải')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='image',
            field=models.ImageField(upload_to='fruit_images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='post_images/'),
        ),
    ]
