# Generated by Django 5.0.4 on 2024-05-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0009_alter_fruit_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='classification',
            field=models.CharField(choices=[('HIGH_CALORIES', 'nhieu-calo'), ('LOW_CALORIES', 'it-calo'), ('MODERATE_CALORIES', 'calo-vua-phai')], max_length=50),
        ),
    ]
