# Generated by Django 5.0.4 on 2024-05-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0010_alter_fruit_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='classification',
            field=models.CharField(choices=[('HIGH_CALORIES', 'Nhiều Calo'), ('LOW_CALORIES', 'Ít Calo'), ('MODERATE_CALORIES', 'Calo Vừa Phải')], max_length=50),
        ),
    ]
