# Generated by Django 5.0.4 on 2024-05-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0011_alter_fruit_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='classification',
            field=models.CharField(choices=[('high_calories', 'Nhiều Calo'), ('low_calories', 'Ít Calo'), ('medium_calories', 'Calo Vừa Phải')], max_length=50),
        ),
    ]
