# Generated by Django 5.0.3 on 2024-05-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0014_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
