# Generated by Django 5.0.6 on 2024-05-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0015_newsitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='unit',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
