# Generated by Django 5.0.3 on 2024-05-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0017_alter_food_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
