# Generated by Django 5.0.6 on 2024-05-31 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0018_alter_food_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='member_images/')),
            ],
        ),
    ]
